version: "2.0"

services:
  dcm-upload:
    build: "."
    environment:
      DEBUG: "false"
      MONGO_URI: "mongodb://a7f80c07dc29344309372718a65abf1c-1759695250.eu-west-3.elb.amazonaws.com:27017/dcm?readPreference=primary&retryWrites=false&maxIdleTimeMS=12000&appname=MongoDB%20Compass&ssl=false"
      SECRET_KEY: "my_precious_secret_key"
      SQLALCHEMY_DATABASE_URI: "sqlite:///urldebase"
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"
      UPLOAD_FOLDER: /scor-data
    ports:
      - "5006:5000"
    volumes:
      - "../scor-data:/scor-data"
